import { businessSchema, serializeJsonLd } from "@/lib/structuredData";
import { pageMetadata } from "@/lib/seo";
import { serviceLandingLinks } from "@/data/landingPages";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Clock3, Headphones, MapPin, Phone, Sparkles } from "lucide-react";
import { PageShell } from "@/components/shared/PageShell";
import { QuickPlanner } from "@/components/home/QuickPlanner";
import { VehicleCards } from "@/components/vehicles/VehicleCards";
import { business } from "@/config/business";
import { faqs, services } from "@/data/content";

export const metadata = pageMetadata("Taxi Service in Wattala & Colombo", "Book taxis, airport transfers, KDH vans, buses, wedding cars and transport services in Wattala, Colombo and across Sri Lanka with PINS Cabs.", "/");

export default function Home() {
  return <PageShell>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(businessSchema) }}/>
    <section className="hero hero--sunset" id="home-top">
      <picture><source media="(max-width: 760px)" srcSet="/media/hero/hero-mobile-v2.webp"/><Image className="hero-image" src="/media/hero/hero-desktop-v2.webp" alt="Illustration of a white sedan on a palm-lined coastal road at sunset" fill loading="eager" fetchPriority="high" sizes="100vw"/></picture><div className="hero-shade"/>
      <div className="hero-route" aria-hidden="true"><span/><i/><b/></div>
      <div className="hero-content shell"><div className="hero-copy"><h1 className="hero-eyebrow"><Sparkles size={15}/>Taxi Service in Wattala &amp; Colombo</h1><div className="hero-slogan"><span>Ride smarter.</span><em>Arrive better.</em></div><p>City taxis and airport transfers from Wattala and Colombo, with transport enquiries across Sri Lanka. Plan your journey with PINS Cabs.</p><div className="hero-actions"><Link className="button button--lime" href="/plan-ride#main-content">Book your ride <ArrowRight size={18}/></Link><Link className="button button--ghost" href="/vehicles#main-content">Explore fleet <ArrowRight size={18}/></Link></div><div className="hero-facts"><span><Clock3/><b>24/7<small>Available</small></b></span><span><Headphones/><b>Personal service<small>Every journey</small></b></span><span><MapPin/><b>Based in<small>Wattala / Colombo</small></b></span></div></div></div>
    </section>
    <div className="planner-wrap hero-planner shell" id="ride-planner"><QuickPlanner/></div>
    <section className="section shell services-section"><div className="section-heading"><div><span className="eyebrow">Choose your journey</span><h2>One place to plan<br/>every kind of ride.</h2></div><p>From everyday cabs and wedding cars to staff transport and long-trip buses, start with what you know and we’ll confirm the rest.</p></div><div className="service-grid">{services.map((service, index) => { const Icon = service.icon; return <Link href={serviceLandingLinks[service.id] || `/plan-ride?service=${service.id}`} className="service-card" key={service.id}><div className="service-media"><Image src={service.image} alt={service.imageAlt} width={1200} height={900}/><span className="service-number">0{index + 1}</span><div className="service-icon"><Icon/></div></div><span className="eyebrow">{service.kicker}</span><h3>{service.name}</h3><p>{service.description}</p><b>{serviceLandingLinks[service.id] ? "Explore this service" : "Plan this trip"} <ArrowRight size={16}/></b></Link>; })}</div></section>
    <section className="dark-section"><div className="section shell"><div className="section-heading light"><div><span className="eyebrow">Cars · Every · KDH vans · buses · lorry</span><h2>A practical fit<br/>for every plan.</h2></div><div><p>Compare Alto, Wagon R, Aqua, Suzuki Every, non-AC vans, KDH vans, 29–55 seater buses, wedding cars and lorry transport. PINS Cabs confirms the exact vehicle and suitability for your journey or load.</p><Link href="/vehicles">View all vehicles <ArrowRight size={16}/></Link></div></div><VehicleCards/></div></section>
    <section className="section shell how-section" id="how-it-works"><div className="how-intro"><span className="eyebrow">How it works</span><h2>From idea to itinerary<br/>in three clear steps.</h2><p>No account, no payment and no automatic booking. You stay in control of the message.</p></div><div className="steps-list"><article><span>01</span><div><h3>Tell us your trip</h3><p>Add pickup, destination, timing and the people travelling.</p></div></article><article><span>02</span><div><h3>Choose your ride</h3><p>Select an illustrative class or ask us to recommend a suitable option.</p></div></article><article><span>03</span><div><h3>Confirm with us</h3><p>Open WhatsApp, send the prepared enquiry, and wait for availability and price confirmation.</p></div></article></div></section>
    <section className="contact-strip"><div className="shell"><div><span className="eyebrow">At your service</span><h2>Wattala-based.<br/>Ready around the clock.</h2></div><div className="contact-details"><a href={`tel:${business.phoneHref}`}><Phone/><span><small>Call PINS Cabs</small>{business.phoneDisplay}</span></a><a href={business.mapUrl} target="_blank" rel="noreferrer"><MapPin/><span><small>Find our base</small>{business.address}</span></a><div><Headphones/><span><small>Operating hours</small>{business.hours}</span></div></div></div></section>
    <section className="section shell checklist-section"><div><span className="eyebrow">Before you send</span><h2>A better enquiry gets you<br/>a clearer answer.</h2></div><div className="checklist">{["Exact pickup and destination","Date and local pickup time","Passenger and luggage count","Flight details, when relevant","Any access or pickup instructions","A preferred vehicle class"].map((item) => <span key={item}><Check size={18}/>{item}</span>)}</div></section>
    <section className="section shell faq-section"><div><span className="eyebrow">Good to know</span><h2>Frequently asked<br/>questions.</h2></div><div className="faq-list">{faqs.map(([q,a], index) => <details key={q} open={index === 0}><summary><span>{q}</span><i>+</i></summary><p>{a}</p></details>)}</div></section>
    <section className="closing"><div className="shell"><span className="eyebrow">Your next ride starts here</span><h2>Where would you<br/>like to go?</h2><Link className="button button--lime" href="/plan-ride">Plan your ride <ArrowRight/></Link></div></section>
  </PageShell>;
}
