import { pageMetadata } from "@/lib/seo";
import { landingPages, serviceLandingLinks } from "@/data/landingPages";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { PageShell } from "@/components/shared/PageShell";
import { services } from "@/data/content";
export const metadata = pageMetadata("Taxi & Transport Services", "Explore PINS Cabs airport transfers, city taxis, outstation journeys, wedding cars, staff transport, buses and lorries.", "/services/");
export default function ServicesPage() { return <PageShell><section className="subpage-hero"><div className="shell"><span className="eyebrow">Ride types</span><h1>One contact.<br/><em>Many ways to go.</em></h1><p>Every trip begins as an enquiry—from wedding arrivals and daily staff routes to long-distance group buses. We’ll confirm the suitable vehicle, availability and final price.</p></div></section><section className="section shell"><div className="service-list">{services.map((service, index) => { const Icon=service.icon; return <article key={service.id}><span className="service-number">0{index+1}</span><div className="service-list-image"><Image src={service.image} alt={service.imageAlt} width={1200} height={900}/><Icon/></div><div><span className="eyebrow">{service.kicker}</span><h2>{service.name}</h2><p>{service.description}</p><ul><li><Check/>Free-text pickup and destination</li><li><Check/>Vehicle preference in one enquiry</li><li><Check/>Direct availability and price confirmation</li></ul></div><Link className="button button--outline" href={serviceLandingLinks[service.id] || `/plan-ride?service=${service.id}`}>{serviceLandingLinks[service.id] ? "Explore service" : "Plan this trip"} <ArrowRight/></Link></article>; })}</div></section><section className="section shell"><h2>Find your service or pickup area</h2><nav className="seo-links" aria-label="All transport services">{landingPages.map(page => <Link key={page.slug} href={"/" + page.slug + "/"}>{page.title}</Link>)}</nav></section></PageShell>; }
